var Module = (() => {
  var _scriptName = import.meta.url;
  
  return (
async function(moduleArg = {}) {
  var moduleRtn;

var h=moduleArg,aa,ba,ca=new Promise((a,b)=>{aa=a;ba=b}),da="object"==typeof window,k="undefined"!=typeof WorkerGlobalScope,m=k&&self.name?.startsWith("em-pthread");h.listenFish=void 0;h.listenZero=void 0;h.zero=a=>ia(a,!1);h.fish=a=>ia(a,!0);h.setZeroWeights=a=>{const b=ja(a.byteLength);if(!b)throw Error(`Could not allocate ${a.byteLength} bytes`);h.HEAPU8.set(a,b);ka(b,a.byteLength)};h.print=a=>{a.startsWith("zero:")?h.listenZero?.(a.slice(5)):a.startsWith("fish:")?h.listenFish?.(a.slice(5)):console.info(a)};
h.printErr=a=>console.error(a);function ia(a,b){const c=q(a)+1,d=ja(c);if(!d)throw Error(`Could not allocate ${c} bytes`);r(a,t,d,c);la(d,b);ma(d)}var na=[],u="",oa,pa;
if(da||k)k?u=self.location.href:"undefined"!=typeof document&&document.currentScript&&(u=document.currentScript.src),_scriptName&&(u=_scriptName),u.startsWith("blob:")?u="":u=u.slice(0,u.replace(/[?#].*/,"").lastIndexOf("/")+1),k&&(pa=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),oa=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);};
var qa=console.log.bind(console),v=console.error.bind(console),x,ra,sa=!1,y,z,t,ta,A,B,C,ua,va=!1;
if(m){var wa,xa=!1;self.onunhandledrejection=b=>{throw b.reason||b;};function a(b){try{var c=b.data,d=c.pa;if("load"===d){let e=[];self.onmessage=f=>e.push(f);self.startWorker=()=>{postMessage({pa:"loaded"});for(let f of e)a(f);self.onmessage=a};for(const f of c.bb)if(!h[f]||h[f].proxy)h[f]=(...g)=>{postMessage({pa:"callHandler",ab:f,Za:g})},"print"==f&&(qa=h[f]),"printErr"==f&&(v=h[f]);x=c.ob;ya();wa(c.pb)}else if("run"===d){za(c.na);Aa(c.na,0,0,1,0,0);Ba();Ca(c.na);xa||=!0;try{Da(c.kb,c.Ha)}catch(e){if("unwind"!=
e)throw e;}}else"setimmediate"!==c.target&&("checkMailbox"===d?xa&&Ea():d&&(v(`worker: received unknown command ${d}`),v(c)))}catch(e){throw Fa(),e;}}self.onmessage=a}function ya(){var a=x.buffer;z=new Int8Array(a);ta=new Int16Array(a);h.HEAPU8=t=new Uint8Array(a);new Uint16Array(a);A=new Int32Array(a);B=new Uint32Array(a);new Float32Array(a);ua=new Float64Array(a);C=new BigInt64Array(a);new BigUint64Array(a)}
function Ga(){m?startWorker(h):(h.noFSInit||Ha||(Ha=!0,Ia("/dev/tty","/dev/stdin"),Ia("/dev/tty","/dev/stdout"),Ia("/dev/tty1","/dev/stderr"),Ja("/dev/stdin",0),Ja("/dev/stdout",1),Ja("/dev/stderr",1)),D.I(),Ka=!1)}var G=0,H=null;function La(){G--;if(0==G&&H){var a=H;H=null;a()}}function I(a){a="Aborted("+a+")";v(a);sa=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ba(a);throw a;}var Ma;
async function Na(a){try{var b=await oa(a);return new Uint8Array(b)}catch{}if(pa)a=pa(a);else throw"both async and sync fetching of the wasm failed";return a}async function Oa(a,b){try{var c=await Na(a);return await WebAssembly.instantiate(c,b)}catch(d){v(`failed to asynchronously prepare wasm: ${d}`),I(d)}}
async function Pa(a){var b=Ma;if("function"==typeof WebAssembly.instantiateStreaming)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){v(`wasm streaming compile failed: ${d}`),v("falling back to ArrayBuffer instantiation")}return Oa(b,a)}function Qa(){Sa={b:Ta,D:Ua,g:Va,w:Wa,x:Xa,y:Ya,k:Za,C:$a,F:ab,o:bb,h:cb,j:Ca,e:db,G:eb,p:fb,H:gb,E:hb,i:ib,l:jb,q:kb,c:lb,B:mb,m:nb,s:ob,t:pb,d:qb,f:rb,v:sb,u:tb,A:ub,z:vb,a:x,n:wb,r:xb};return{a:Sa}}
class yb{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var zb=a=>{a.terminate();a.onmessage=()=>{}},Ab=[],Cb=a=>{if(0==J.length){if(h.mainScriptUrlOrBlob){var b=h.mainScriptUrlOrBlob;"string"!=typeof b&&(b=URL.createObjectURL(b));b=new Worker(b,{type:"module",name:"em-pthread"})}else b=new Worker(new URL("zerofishEngine.js",import.meta.url),{type:"module",name:"em-pthread"});J.push(b);Bb()}b=J.pop();if(!b)return 6;K.push(b);L[a.na]=b;b.na=a.na;b.postMessage({pa:"run",kb:a.jb,Ha:a.Ha,na:a.na},a.Xa);return 0},M=0,nb=()=>0<M,N=(a,b,...c)=>{for(var d=
2*c.length,e=Db(),f=Eb(8*d),g=f>>3,l=0;l<c.length;l++){var p=c[l];"bigint"==typeof p?(C[g+2*l]=1n,C[g+2*l+1]=p):(C[g+2*l]=0n,ua[g+2*l+1]=p)}a=Fb(a,0,d,f,b);Gb(e);return a};function wb(a){if(m)return N(0,1,a);y=a;0<M||(Hb(),sa=!0);throw new yb(a);}function Ib(a){if(m)return N(1,0,a);--M;qb(a)}
var qb=a=>{y=a;if(m)throw Ib(a),"unwind";if(!(0<M||m)){Jb();Ha=!1;Kb(0);for(var b of P)b&&Lb(b);Hb();va=!0}wb(a)},J=[],K=[],Mb=[],L={},Hb=()=>{for(var a of K)zb(a);for(a of J)zb(a);J=[];K=[];L={}},Ob=a=>{var b=a.na;delete L[b];J.push(a);K.splice(K.indexOf(a),1);a.na=0;Nb(b)};function Ba(){Mb.forEach(a=>a())}
var Bb=()=>{var a=J[0];new Promise(b=>{a.onmessage=f=>{f=f.data;var g=f.pa;if(f.Ga&&f.Ga!=Pb()){var l=L[f.Ga];l?l.postMessage(f,f.Xa):v(`Internal error! Worker sent a message "${g}" to target pthread ${f.Ga}, but that thread no longer exists!`)}else if("checkMailbox"===g)Ea();else if("spawnThread"===g)Cb(f);else if("cleanupThread"===g)Ob(L[f.lb]);else if("loaded"===g)a.loaded=!0,b(a);else if("setimmediate"===f.target)a.postMessage(f);else if("callHandler"===g)h[f.ab](...f.Za);else g&&v(`worker sent an unknown command ${g}`)};
a.onerror=f=>{v(`${"worker sent an error!"} ${f.filename}:${f.lineno}: ${f.message}`);throw f;};var c=[],d=["print","printErr"],e;for(e of d)h.propertyIsEnumerable(e)&&c.push(e);a.postMessage({pa:"load",bb:c,ob:x,pb:ra})})},za=a=>{var b=B[a+52>>2];Qb(b,b-B[a+56>>2]);Gb(b)},Rb=[],Sb,Da=(a,b)=>{M=0;var c=Rb[a];c||(Rb[a]=c=Sb.get(a));a=c(b);0<M?y=a:Tb(a)};class Ub{constructor(a){this.Da=a-24}}
var Vb=0,Wb=0,Ta=(a,b,c)=>{var d=new Ub(a);B[d.Da+16>>2]=0;B[d.Da+4>>2]=b;B[d.Da+8>>2]=c;Vb=a;Wb++;throw Vb;};function Xb(a,b,c,d){return m?N(2,1,a,b,c,d):Ua(a,b,c,d)}
var Ua=(a,b,c,d)=>{if("undefined"==typeof SharedArrayBuffer)return 6;var e=[];if(m&&0===e.length)return Xb(a,b,c,d);a={jb:c,na:a,Ha:d,Xa:e};return m?(a.pa="spawnThread",postMessage(a,e),0):Cb(a)},Q=()=>{var a=A[+Yb>>2];Yb+=4;return a},Zb=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},$b=a=>{var b="/"===a.charAt(0),c="/"===a.slice(-1);(a=Zb(a.split("/").filter(d=>!!d),!b).join("/"))||
b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},ac=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.slice(0,-1);return a+b},bc=()=>a=>a.set(crypto.getRandomValues(new Uint8Array(a.byteLength))),cc=a=>{(cc=bc())(a)},dc=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:"/";if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=
Zb(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},ec="undefined"!=typeof TextDecoder?new TextDecoder:void 0,R=(a,b=0)=>{for(var c=b+NaN,d=b;a[d]&&!(d>=c);)++d;if(16<d-b&&a.buffer&&ec)return ec.decode(a.buffer instanceof ArrayBuffer?a.subarray(b,d):a.slice(b,d));for(c="";b<d;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))c+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?c+=String.fromCharCode(e):
(e-=65536,c+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}return c},fc=[],q=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},r=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var l=a.charCodeAt(++f);g=65536+((g&1023)<<10)|l&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=
g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-e},gc=[];function hc(a,b){gc[a]={input:[],output:[],sa:b};ic(a,jc)}
var jc={open(a){var b=gc[a.node.Ea];if(!b)throw new S(43);a.ha=b;a.seekable=!1},close(a){a.ha.sa.Aa(a.ha)},Aa(a){a.ha.sa.Aa(a.ha)},read(a,b,c,d){if(!a.ha||!a.ha.sa.Qa)throw new S(60);for(var e=0,f=0;f<d;f++){try{var g=a.ha.sa.Qa(a.ha)}catch(l){throw new S(29);}if(void 0===g&&0===e)throw new S(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.va=Date.now());return e},write(a,b,c,d){if(!a.ha||!a.ha.sa.La)throw new S(60);try{for(var e=0;e<d;e++)a.ha.sa.La(a.ha,b[c+e])}catch(f){throw new S(29);
}d&&(a.node.ka=a.node.ja=Date.now());return e}},kc={Qa(){a:{if(!fc.length){var a=null;"undefined"!=typeof window&&"function"==typeof window.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){var b=null;break a}b=Array(q(a)+1);a=r(a,b,0,b.length);b.length=a;fc=b}b=fc.shift()}return b},La(a,b){null===b||10===b?(qa(R(a.output)),a.output=[]):0!=b&&a.output.push(b)},Aa(a){0<a.output?.length&&(qa(R(a.output)),a.output=[])},eb(){return{vb:25856,xb:5,ub:191,wb:35387,tb:[3,28,127,21,4,0,1,0,17,
19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},fb(){return 0},gb(){return[24,80]}},lc={La(a,b){null===b||10===b?(v(R(a.output)),a.output=[]):0!=b&&a.output.push(b)},Aa(a){0<a.output?.length&&(v(R(a.output)),a.output=[])}},T={ma:null,ra(){return T.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new S(63);T.ma||(T.ma={dir:{node:{ua:T.ga.ua,oa:T.ga.oa,xa:T.ga.xa,Ba:T.ga.Ba,Va:T.ga.Va,Ya:T.ga.Ya,Wa:T.ga.Wa,Ma:T.ga.Ma,Fa:T.ga.Fa},stream:{la:T.ea.la}},
file:{node:{ua:T.ga.ua,oa:T.ga.oa},stream:{la:T.ea.la,read:T.ea.read,write:T.ea.write,Sa:T.ea.Sa,Ua:T.ea.Ua}},link:{node:{ua:T.ga.ua,oa:T.ga.oa,ya:T.ga.ya},stream:{}},Oa:{node:{ua:T.ga.ua,oa:T.ga.oa},stream:mc}});c=nc(a,b,c,d);16384===(c.mode&61440)?(c.ga=T.ma.dir.node,c.ea=T.ma.dir.stream,c.fa={}):32768===(c.mode&61440)?(c.ga=T.ma.file.node,c.ea=T.ma.file.stream,c.ia=0,c.fa=null):40960===(c.mode&61440)?(c.ga=T.ma.link.node,c.ea=T.ma.link.stream):8192===(c.mode&61440)&&(c.ga=T.ma.Oa.node,c.ea=T.ma.Oa.stream);
c.va=c.ka=c.ja=Date.now();a&&(a.fa[b]=c,a.va=a.ka=a.ja=c.va);return c},Bb(a){return a.fa?a.fa.subarray?a.fa.subarray(0,a.ia):new Uint8Array(a.fa):new Uint8Array(0)},ga:{ua(a){var b={};b.yb=8192===(a.mode&61440)?a.id:1;b.Db=a.id;b.mode=a.mode;b.Eb=1;b.uid=0;b.Cb=0;b.Ea=a.Ea;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.ia:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.va=new Date(a.va);b.ka=new Date(a.ka);b.ja=new Date(a.ja);b.$a=4096;b.sb=Math.ceil(b.size/b.$a);return b},
oa(a,b){for(var c of["mode","atime","mtime","ctime"])null!=b[c]&&(a[c]=b[c]);void 0!==b.size&&(b=b.size,a.ia!=b&&(0==b?(a.fa=null,a.ia=0):(c=a.fa,a.fa=new Uint8Array(b),c&&a.fa.set(c.subarray(0,Math.min(b,a.ia))),a.ia=b)))},xa(){throw T.Pa;},Ba(a,b,c,d){return T.createNode(a,b,c,d)},Va(a,b,c){try{var d=oc(b,c)}catch(f){}if(d){if(16384===(a.mode&61440))for(var e in d.fa)throw new S(55);e=pc(d.parent.id,d.name);if(U[e]===d)U[e]=d.wa;else for(e=U[e];e;){if(e.wa===d){e.wa=d.wa;break}e=e.wa}}delete a.parent.fa[a.name];
b.fa[c]=a;a.name=c;b.ja=b.ka=a.parent.ja=a.parent.ka=Date.now()},Ya(a,b){delete a.fa[b];a.ja=a.ka=Date.now()},Wa(a,b){var c=oc(a,b),d;for(d in c.fa)throw new S(55);delete a.fa[b];a.ja=a.ka=Date.now()},Ma(a){return[".","..",...Object.keys(a.fa)]},Fa(a,b,c){a=T.createNode(a,b,41471,0);a.link=c;return a},ya(a){if(40960!==(a.mode&61440))throw new S(28);return a.link}},ea:{read(a,b,c,d,e){var f=a.node.fa;if(e>=a.node.ia)return 0;a=Math.min(a.node.ia-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=
0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){if(!d)return 0;a=a.node;a.ka=a.ja=Date.now();if(b.subarray&&(!a.fa||a.fa.subarray)){if(f)return a.fa=b.subarray(c,c+d),a.ia=d;if(0===a.ia&&0===e)return a.fa=b.slice(c,c+d),a.ia=d;if(e+d<=a.ia)return a.fa.set(b.subarray(c,c+d),e),d}f=e+d;var g=a.fa?a.fa.length:0;g>=f||(f=Math.max(f,g*(1048576>g?2:1.125)>>>0),0!=g&&(f=Math.max(f,256)),g=a.fa,a.fa=new Uint8Array(f),0<a.ia&&a.fa.set(g.subarray(0,a.ia),0));if(a.fa.subarray&&b.subarray)a.fa.set(b.subarray(c,
c+d),e);else for(f=0;f<d;f++)a.fa[e+f]=b[c+f];a.ia=Math.max(a.ia,e+d);return d},la(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.ia);if(0>b)throw new S(28);return b},Sa(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new S(43);a=a.node.fa;if(e&2||!a||a.buffer!==z.buffer){d=!0;I();e=void 0;if(!e)throw new S(48);if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);z.set(a,e)}}else d=!1,e=a.byteOffset;return{Da:e,rb:d}},Ua(a,b,c,
d){T.ea.write(a,b,0,d,c,!1);return 0}}},qc=a=>{var b=0;a&&(b|=365);return b},rc=null,sc={},P=[],tc=1,U=null,Ha=!1,Ka=!0,S=class{name="ErrnoError";constructor(a){this.qa=a}},uc=class{za={};node=null;get flags(){return this.za.flags}set flags(a){this.za.flags=a}get position(){return this.za.position}set position(a){this.za.position=a}},vc=class{ga={};ea={};Ca=null;constructor(a,b,c,d){a||=this;this.parent=a;this.ra=a.ra;this.id=tc++;this.name=b;this.mode=c;this.Ea=d;this.va=this.ka=this.ja=Date.now()}get read(){return 365===
(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}};
function W(a,b={}){if(!a)throw new S(44);b.Ja??(b.Ja=!0);"/"===a.charAt(0)||(a="//"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(l=>!!l);for(var d=rc,e="/",f=0;f<a.length;f++){var g=f===a.length-1;if(g&&b.parent)break;if("."!==a[f])if(".."===a[f])if(e=ac(e),d===d.parent){a=e+"/"+a.slice(f+1).join("/");continue a}else d=d.parent;else{e=$b(e+"/"+a[f]);try{d=oc(d,a[f])}catch(l){if(44===l?.qa&&g&&b.ib)return{path:e};throw l;}!d.Ca||g&&!b.Ja||(d=d.Ca.root);if(40960===(d.mode&61440)&&(!g||b.Ia)){if(!d.ga.ya)throw new S(52);
d=d.ga.ya(d);"/"===d.charAt(0)||(d=ac(e)+"/"+d);a=d+"/"+a.slice(f+1).join("/");continue a}}}return{path:e,node:d}}throw new S(32);}function pc(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%U.length}function oc(a,b){var c=16384===(a.mode&61440)?(c=wc(a,"x"))?c:a.ga.xa?0:2:54;if(c)throw new S(c);for(c=U[pc(a.id,b)];c;c=c.wa){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.ga.xa(a,b)}
function nc(a,b,c,d){a=new vc(a,b,c,d);b=pc(a.parent.id,a.name);a.wa=U[b];return U[b]=a}function xc(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function wc(a,b){if(Ka)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function yc(a,b){if(16384!==(a.mode&61440))return 54;try{return oc(a,b),20}catch(c){}return wc(a,"wx")}function X(a){a=P[a];if(!a)throw new S(8);return a}
function zc(a,b=-1){a=Object.assign(new uc,a);if(-1==b)a:{for(b=0;4096>=b;b++)if(!P[b])break a;throw new S(33);}a.ta=b;return P[b]=a}function Ac(a,b=-1){a=zc(a,b);a.ea?.Ab?.(a);return a}function Bc(a,b){var c=null?.ea.oa,d=c?null:a;c??=a.ga.oa;if(!c)throw new S(63);c(d,b)}var mc={open(a){a.ea=sc[a.node.Ea].ea;a.ea.open?.(a)},la(){throw new S(70);}};function ic(a,b){sc[a]={ea:b}}
function Cc(a,b){var c="/"===b;if(c&&rc)throw new S(10);if(!c&&b){var d=W(b,{Ja:!1});b=d.path;d=d.node;if(d.Ca)throw new S(10);if(16384!==(d.mode&61440))throw new S(54);}b={type:a,Fb:{},Ta:b,hb:[]};a=a.ra(b);a.ra=b;b.root=a;c?rc=a:d&&(d.Ca=b,d.ra&&d.ra.hb.push(b))}function Dc(a,b,c){var d=W(a,{parent:!0}).node;a=a&&a.match(/([^\/]+|\/)\/*$/)[1];if(!a)throw new S(28);if("."===a||".."===a)throw new S(20);var e=yc(d,a);if(e)throw new S(e);if(!d.ga.Ba)throw new S(63);return d.ga.Ba(d,a,b,c)}
function Y(a){return Dc(a,16895,0)}function Ec(a,b,c){"undefined"==typeof c&&(c=b,b=438);Dc(a,b|8192,c)}function Ia(a,b){if(!dc(a))throw new S(44);var c=W(b,{parent:!0}).node;if(!c)throw new S(44);b=b&&b.match(/([^\/]+|\/)\/*$/)[1];var d=yc(c,b);if(d)throw new S(d);if(!c.ga.Fa)throw new S(63);c.ga.Fa(c,b,a)}
function Ja(a,b,c=438){if(""===a)throw new S(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;if("object"==typeof a)d=a;else{var e=a.endsWith("/");var f=W(a,{Ia:!(b&131072),ib:!0});d=f.node;a=f.path}f=!1;if(b&64)if(d){if(b&128)throw new S(20);}else{if(e)throw new S(31);d=Dc(a,c|511,0);f=!0}if(!d)throw new S(44);8192===(d.mode&61440)&&(b&=-513);if(b&65536&&16384!==(d.mode&
61440))throw new S(54);if(!f&&(e=d?40960===(d.mode&61440)?32:16384===(d.mode&61440)&&("r"!==xc(b)||b&576)?31:wc(d,xc(b)):44))throw new S(e);if(b&512&&!f){e=d;e="string"==typeof e?W(e,{Ia:!0}).node:e;if(16384===(e.mode&61440))throw new S(31);if(32768!==(e.mode&61440))throw new S(28);if(a=wc(e,"w"))throw new S(a);Bc(e,{size:0,timestamp:Date.now()})}a:for(e=d;;){if(e===e.parent){e=e.ra.Ta;var g=g?"/"!==e[e.length-1]?`${e}/${g}`:e+g:e;break a}g=g?`${e.name}/${g}`:e.name;e=e.parent}b=zc({node:d,path:g,
flags:b&-131713,seekable:!0,position:0,ea:d.ea,mb:[],error:!1});b.ea.open&&b.ea.open(b);f&&(c&=511,d="string"==typeof d?W(d,{Ia:!0}).node:d,Bc(d,{mode:c&4095|d.mode&-4096,ja:Date.now(),zb:void 0}));return b}function Lb(a){if(null===a.ta)throw new S(8);a.Ka&&(a.Ka=null);try{a.ea.close&&a.ea.close(a)}catch(b){throw b;}finally{P[a.ta]=null}a.ta=null}
function Fc(a,b,c){if(null===a.ta)throw new S(8);if(!a.seekable||!a.ea.la)throw new S(70);if(0!=c&&1!=c&&2!=c)throw new S(28);a.position=a.ea.la(a,b,c);a.mb=[]}
function Gc(a,b){a=$b("/dev/"+a);var c=qc(!!b);Gc.Ra??(Gc.Ra=64);var d=Gc.Ra++<<8|0;ic(d,{open(e){e.seekable=!1},close(){(void 0)?.buffer?.length&&(void 0)(10)},read(e,f,g,l){for(var p=0,n=0;n<l;n++){try{var w=b()}catch(V){throw new S(29);}if(void 0===w&&0===p)throw new S(6);if(null===w||void 0===w)break;p++;f[g+n]=w}p&&(e.node.va=Date.now());return p},write(e,f,g,l){for(var p=0;p<l;p++)try{(void 0)(f[g+p])}catch(n){throw new S(29);}l&&(e.node.ka=e.node.ja=Date.now());return p}});Ec(a,c,d)}
var Z={},Yb=void 0;function Va(a,b,c){if(m)return N(3,1,a,b,c);Yb=c;try{var d=X(a);switch(b){case 0:var e=Q();if(0>e)break;for(;P[e];)e++;return Ac(d,e).ta;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=Q(),d.flags|=e,0;case 12:return e=Q(),ta[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(f){if("undefined"==typeof Z||"ErrnoError"!==f.name)throw f;return-f.qa}}
function Wa(a,b,c){if(m)return N(4,1,a,b,c);Yb=c;try{var d=X(a);switch(b){case 21509:return d.ha?0:-59;case 21505:if(!d.ha)return-59;if(d.ha.sa.eb){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=Q();A[e>>2]=25856;A[e+4>>2]=5;A[e+8>>2]=191;A[e+12>>2]=35387;for(var f=0;32>f;f++)z[e+f+17]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.ha?0:-59;case 21506:case 21507:case 21508:if(!d.ha)return-59;if(d.ha.sa.fb)for(e=Q(),a=[],f=0;32>f;f++)a.push(z[e+f+17]);
return 0;case 21519:if(!d.ha)return-59;e=Q();return A[e>>2]=0;case 21520:return d.ha?-28:-59;case 21531:e=Q();if(!d.ea.cb)throw new S(59);return d.ea.cb(d,b,e);case 21523:if(!d.ha)return-59;d.ha.sa.gb&&(f=[24,80],e=Q(),ta[e>>1]=f[0],ta[e+2>>1]=f[1]);return 0;case 21524:return d.ha?0:-59;case 21515:return d.ha?0:-59;default:return-28}}catch(g){if("undefined"==typeof Z||"ErrnoError"!==g.name)throw g;return-g.qa}}
function Xa(a,b,c,d){if(m)return N(5,1,a,b,c,d);Yb=d;try{b=b?R(t,b):"";var e=b;if("/"===e.charAt(0))b=e;else{var f=-100===a?"/":X(a).path;if(0==e.length)throw new S(44);b=f+"/"+e}var g=d?Q():0;return Ja(b,c,g).ta}catch(l){if("undefined"==typeof Z||"ErrnoError"!==l.name)throw l;return-l.qa}}
var Ya=()=>I(""),Za=a=>{Aa(a,!k,1,!da,1048576,!1);Ba()},Hc=a=>{if(a instanceof yb||"unwind"==a)return y;throw a;},Ic=a=>{if(!va&&!sa)try{if(a(),!(va||0<M))try{m?Tb(y):qb(y)}catch(b){Hc(b)}}catch(b){Hc(b)}},Ca=a=>{"function"===typeof Atomics.nb&&(Atomics.nb(A,a>>2,a).value.then(Ea),Atomics.store(A,a+128>>2,1))},Ea=()=>{var a=Pb();a&&(Ca(a),Ic(Jc))},$a=(a,b)=>{a==b?setTimeout(Ea):m?postMessage({Ga:a,pa:"checkMailbox"}):(a=L[a])&&a.postMessage({pa:"checkMailbox"})},Kc=[],ab=(a,b,c,d,e)=>{d/=2;Kc.length=
d;b=e>>3;for(c=0;c<d;c++)Kc[c]=C[b+2*c]?C[b+2*c+1]:ua[b+2*c+1];return(0,Lc[a])(...Kc)},bb=()=>{M=0},cb=a=>{m?postMessage({pa:"cleanupThread",lb:a}):Ob(L[a])},db=()=>{},Mc=[0,31,60,91,121,152,182,213,244,274,305,335],Nc=[0,31,59,90,120,151,181,212,243,273,304,334];
function eb(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);a=new Date(1E3*a);A[b>>2]=a.getSeconds();A[b+4>>2]=a.getMinutes();A[b+8>>2]=a.getHours();A[b+12>>2]=a.getDate();A[b+16>>2]=a.getMonth();A[b+20>>2]=a.getFullYear()-1900;A[b+24>>2]=a.getDay();var c=a.getFullYear();A[b+28>>2]=(0!==c%4||0===c%100&&0!==c%400?Nc:Mc)[a.getMonth()]+a.getDate()-1|0;A[b+36>>2]=-(60*a.getTimezoneOffset());c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();var d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();
A[b+32>>2]=(c!=d&&a.getTimezoneOffset()==Math.min(d,c))|0}var Oc={},lb=()=>performance.timeOrigin+performance.now();function fb(a,b){if(m)return N(6,1,a,b);Oc[a]&&(clearTimeout(Oc[a].id),delete Oc[a]);if(!b)return 0;var c=setTimeout(()=>{delete Oc[a];Ic(()=>Pc(a,performance.timeOrigin+performance.now()))},b);Oc[a]={id:c,Gb:b};return 0}
var gb=(a,b,c,d)=>{var e=(new Date).getFullYear(),f=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();B[a>>2]=60*Math.max(f,e);A[b>>2]=Number(f!=e);b=g=>{var l=Math.abs(g);return`UTC${0<=g?"-":"+"}${String(Math.floor(l/60)).padStart(2,"0")}${String(l%60).padStart(2,"0")}`};a=b(f);b=b(e);e<f?(r(a,t,c,17),r(b,t,d,17)):(r(a,t,d,17),r(b,t,c,17))},Qc=1;
function hb(a,b,c){if(!(0<=a&&3>=a))return 28;if(0===a)a=Date.now();else if(Qc)a=performance.timeOrigin+performance.now();else return 52;C[c>>3]=BigInt(Math.round(1E6*a));return 0}
var Rc=()=>{Rc.Na||(Rc.Na={});Rc.Na["Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"]||(Rc.Na["Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"]=1,v("Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"))},ib=()=>{k||(Rc(),I("Blocking on the main thread is not allowed by default. See https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"))},
jb=()=>{M+=1;throw"unwind";},kb=(a,b,c)=>{var d=Error().stack.toString(),e=d.split("\n");d="";var f=RegExp("\\s*(.*?)@(.*?):([0-9]+):([0-9]+)"),g=RegExp("\\s*at (.*?) \\((.*):(.*):(.*)\\)"),l;for(l of e){var p=g.exec(l);if(5==p?.length){e=p[1];var n=p[2];var w=p[3];p=p[4]}else if(p=f.exec(l),4<=p?.length)e=p[1],n=p[2],w=p[3],p=p[4]|0;else{d+=l+"\n";continue}"_emscripten_log"==e||"_emscripten_get_callstack"==e?d="":a&24&&(a&64&&(n=n.substring(n.replace(/\\/g,"/").lastIndexOf("/")+1)),d+=`    at ${e} (${n}:${w}:${p})\n`)}a=
d=d.replace(/\s+$/,"");return!b||0>=c?q(a)+1:r(a,t,b,c)+1},mb=()=>{I("OOM")},Sc={},Uc=()=>{if(!Tc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:"./this.program"},b;for(b in Sc)void 0===Sc[b]?delete a[b]:a[b]=Sc[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Tc=c}return Tc},Tc;
function ob(a,b){if(m)return N(7,1,a,b);var c=0,d=0,e;for(e of Uc()){var f=b+c;B[a+d>>2]=f;c+=r(e,t,f,Infinity)+1;d+=4}return 0}function pb(a,b){if(m)return N(8,1,a,b);var c=Uc();B[a>>2]=c.length;a=0;for(var d of c)a+=q(d)+1;B[b>>2]=a;return 0}function rb(a){if(m)return N(9,1,a);try{var b=X(a);Lb(b);return 0}catch(c){if("undefined"==typeof Z||"ErrnoError"!==c.name)throw c;return c.qa}}
function sb(a,b,c,d){if(m)return N(10,1,a,b,c,d);try{a:{var e=X(a);a=b;for(var f,g=b=0;g<c;g++){var l=B[a>>2],p=B[a+4>>2];a+=8;var n=e,w=l,V=p,E=f,Ra=z;if(0>V||0>E)throw new S(28);if(null===n.ta)throw new S(8);if(1===(n.flags&2097155))throw new S(8);if(16384===(n.node.mode&61440))throw new S(31);if(!n.ea.read)throw new S(28);var ea="undefined"!=typeof E;if(!ea)E=n.position;else if(!n.seekable)throw new S(70);var fa=n.ea.read(n,Ra,w,V,E);ea||(n.position+=fa);var F=fa;if(0>F){var ha=-1;break a}b+=F;
if(F<p)break;"undefined"!=typeof f&&(f+=F)}ha=b}B[d>>2]=ha;return 0}catch(O){if("undefined"==typeof Z||"ErrnoError"!==O.name)throw O;return O.qa}}function tb(a,b,c,d){if(m)return N(11,1,a,b,c,d);b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return 61;var e=X(a);Fc(e,b,c);C[d>>3]=BigInt(e.position);e.Ka&&0===b&&0===c&&(e.Ka=null);return 0}catch(f){if("undefined"==typeof Z||"ErrnoError"!==f.name)throw f;return f.qa}}
function ub(a,b,c,d){if(m)return N(12,1,a,b,c,d);try{a:{var e=X(a);a=b;for(var f,g=b=0;g<c;g++){var l=B[a>>2],p=B[a+4>>2];a+=8;var n=e,w=l,V=p,E=f,Ra=z;if(0>V||0>E)throw new S(28);if(null===n.ta)throw new S(8);if(0===(n.flags&2097155))throw new S(8);if(16384===(n.node.mode&61440))throw new S(31);if(!n.ea.write)throw new S(28);n.seekable&&n.flags&1024&&Fc(n,0,2);var ea="undefined"!=typeof E;if(!ea)E=n.position;else if(!n.seekable)throw new S(70);var fa=n.ea.write(n,Ra,w,V,E,void 0);ea||(n.position+=
fa);var F=fa;if(0>F){var ha=-1;break a}b+=F;if(F<p)break;"undefined"!=typeof f&&(f+=F)}ha=b}B[d>>2]=ha;return 0}catch(O){if("undefined"==typeof Z||"ErrnoError"!==O.name)throw O;return O.qa}}function xb(a,b){try{return cc(t.subarray(a,a+b)),0}catch(c){if("undefined"==typeof Z||"ErrnoError"!==c.name)throw c;return c.qa}}m||Ab.push(()=>{G++;La()});U=Array(4096);Cc(T,"/");Y("/tmp");Y("/home");Y("/home/web_user");
(function(){Y("/dev");ic(259,{read:()=>0,write:(d,e,f,g)=>g,la:()=>0});Ec("/dev/null",259);hc(1280,kc);hc(1536,lc);Ec("/dev/tty",1280);Ec("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(cc(a),b=a.byteLength);return a[--b]};Gc("random",c);Gc("urandom",c);Y("/dev/shm");Y("/dev/shm/tmp")})();
(function(){Y("/proc");var a=Y("/proc/self");Y("/proc/self/fd");Cc({ra(){var b=nc(a,"fd",16895,73);b.ea={la:T.ea.la};b.ga={xa(c,d){c=+d;var e=X(c);c={parent:null,ra:{Ta:"fake"},ga:{ya:()=>e.path},id:c+1};return c.parent=c},Ma(){return Array.from(P.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},"/proc/self/fd")})();T.Pa=new S(44);T.Pa.stack="<generic error, no stack>";m||(x=new WebAssembly.Memory({initial:2560,maximum:2560,shared:!0}),ya());h.print&&(qa=h.print);
h.printErr&&(v=h.printErr);h.callMain=Vc;h.stringToUTF8=(a,b,c)=>r(a,t,b,c);h.lengthBytesUTF8=q;var Lc=[wb,Ib,Xb,Va,Wa,Xa,fb,ob,pb,rb,sb,tb,ub];function vb(a){h.qb(a?R(t,a):"")}
var Sa,D=await (async function(){function a(d,e){D=d.exports;Mb.push(D.Q);Sb=D.S;ra=e;La();return D}G++;var b=Qa();if(m)return new Promise(d=>{wa=e=>{var f=new WebAssembly.Instance(e,Qa());d(a(f,e))}});Ma??=h.locateFile?h.locateFile?h.locateFile("zerofishEngine.wasm",u):u+"zerofishEngine.wasm":(new URL("zerofishEngine.wasm",import.meta.url)).href;try{var c=await Pa(b);return a(c.instance,c.module)}catch(d){return ba(d),Promise.reject(d)}}()),ja=h._malloc=a=>(ja=h._malloc=D.J)(a),
ma=h._free=a=>(ma=h._free=D.K)(a),Pb=()=>(Pb=D.L)();h._main=(a,b)=>(h._main=D.M)(a,b);var la=h._uci=(a,b)=>(la=h._uci=D.N)(a,b),ka=h._set_weights=(a,b)=>(ka=h._set_weights=D.O)(a,b);h._quit=()=>(h._quit=D.P)();
var Wc=h.__emscripten_proxy_main=(a,b)=>(Wc=h.__emscripten_proxy_main=D.R)(a,b),Jb=()=>(Jb=D.T)(),Aa=(a,b,c,d,e,f)=>(Aa=D.U)(a,b,c,d,e,f),Fa=()=>(Fa=D.V)(),Kb=a=>(Kb=D.W)(a),Fb=(a,b,c,d,e)=>(Fb=D.X)(a,b,c,d,e),Nb=a=>(Nb=D.Y)(a),Tb=a=>(Tb=D.Z)(a),Pc=(a,b)=>(Pc=D._)(a,b),Jc=()=>(Jc=D.$)(),Qb=(a,b)=>(Qb=D.aa)(a,b),Gb=a=>(Gb=D.ba)(a),Eb=a=>(Eb=D.ca)(a),Db=()=>(Db=D.da)();
function Vc(a=[]){var b=Wc;M+=1;a.unshift("./this.program");var c=a.length,d=Eb(4*(c+1)),e=d;a.forEach(g=>{var l=B,p=e>>2,n=q(g)+1,w=Eb(n);r(g,t,w,n);l[p]=w;e+=4});B[e>>2]=0;try{var f=b(c,d);qb(f,!0);return f}catch(g){return Hc(g)}}function Xc(a=na){if(0<G)H=Xc;else if(m)aa(h),Ga();else{for(;0<Ab.length;)Ab.shift()(h);0<G?H=Xc:(h.calledRun=!0,sa||(Ga(),aa(h),h.noInitialRun||Vc(a)))}}Xc();moduleRtn=ca;


  return moduleRtn;
}
);
})();
export default Module;
var isPthread = globalThis.self?.name?.startsWith('em-pthread');
// When running as a pthread, construct a new instance on startup
isPthread && Module();
